/*
 * body_codes.c
 *
 * Created: 06/03/2016 16:42
 *  Author: Tyler
 */ 

#include <avr/io.h>
#include <string.h>
#include <stdio.h>

#include "body_codes.h"

const lcd_character LEFT_NAME_1 = {
	LEFT_NAME_1_A,
	LEFT_NAME_1_B,
	LEFT_NAME_1_C,
	LEFT_NAME_1_D,
	LEFT_NAME_1_E,
	LEFT_NAME_1_F,
	LEFT_NAME_1_G1,
	LEFT_NAME_1_G2,
	LEFT_NAME_1_H,
	LEFT_NAME_1_IL,
	LEFT_NAME_1_J,
	LEFT_NAME_1_K,
	LEFT_NAME_1_M,
	LEFT_NAME_1_DP};

const lcd_character LEFT_NAME_2 = {
	LEFT_NAME_2_A,
	LEFT_NAME_2_B,
	LEFT_NAME_2_C,
	LEFT_NAME_2_D,
	LEFT_NAME_2_E,
	LEFT_NAME_2_F,
	LEFT_NAME_2_G1,
	LEFT_NAME_2_G2,
	LEFT_NAME_2_H,
	LEFT_NAME_2_IL,
	LEFT_NAME_2_J,
	LEFT_NAME_2_K,
	LEFT_NAME_2_M,
	LEFT_NAME_2_DP};

const lcd_character LEFT_NAME_3 = {
	LEFT_NAME_3_A,
	LEFT_NAME_3_B,
	LEFT_NAME_3_C,
	LEFT_NAME_3_D,
	LEFT_NAME_3_E,
	LEFT_NAME_3_F,
	LEFT_NAME_3_G1,
	LEFT_NAME_3_G2,
	LEFT_NAME_3_H,
	LEFT_NAME_3_IL,
	LEFT_NAME_3_J,
	LEFT_NAME_3_K,
	LEFT_NAME_3_M,
	LEFT_NAME_3_DP};

const lcd_character LEFT_NAME_4 = {
	LEFT_NAME_4_A,
	LEFT_NAME_4_B,
	LEFT_NAME_4_C,
	LEFT_NAME_4_D,
	LEFT_NAME_4_E,
	LEFT_NAME_4_F,
	LEFT_NAME_4_G1,
	LEFT_NAME_4_G2,
	LEFT_NAME_4_H,
	LEFT_NAME_4_IL,
	LEFT_NAME_4_J,
	LEFT_NAME_4_K,
	LEFT_NAME_4_M,
	LEFT_NAME_4_DP};

const lcd_character LEFT_NAME_5 = {
	LEFT_NAME_5_A,
	LEFT_NAME_5_B,
	LEFT_NAME_5_C,
	LEFT_NAME_5_D,
	LEFT_NAME_5_E,
	LEFT_NAME_5_F,
	LEFT_NAME_5_G1,
	LEFT_NAME_5_G2,
	LEFT_NAME_5_H,
	LEFT_NAME_5_IL,
	LEFT_NAME_5_J,
	LEFT_NAME_5_K,
	LEFT_NAME_5_M,
	LEFT_NAME_5_DP};

const lcd_character LEFT_NAME_6 = {
	LEFT_NAME_6_A,
	LEFT_NAME_6_B,
	LEFT_NAME_6_C,
	LEFT_NAME_6_D,
	LEFT_NAME_6_E,
	LEFT_NAME_6_F,
	LEFT_NAME_6_G1,
	LEFT_NAME_6_G2,
	LEFT_NAME_6_H,
	LEFT_NAME_6_IL,
	LEFT_NAME_6_J,
	LEFT_NAME_6_K,
	LEFT_NAME_6_M,
	LEFT_NAME_6_DP};

const lcd_character* LEFT_NAME_CHARACTERS[6] = {&LEFT_NAME_1,&LEFT_NAME_2,&LEFT_NAME_3,&LEFT_NAME_4,&LEFT_NAME_5,&LEFT_NAME_6};
const lcd_string LEFT_NAME = {.length=6,.characters=LEFT_NAME_CHARACTERS};
	
const lcd_character RIGHT_NAME_1 = {
	RIGHT_NAME_1_A,
	RIGHT_NAME_1_B,
	RIGHT_NAME_1_C,
	RIGHT_NAME_1_D,
	RIGHT_NAME_1_E,
	RIGHT_NAME_1_F,
	RIGHT_NAME_1_G1,
	RIGHT_NAME_1_G2,
	RIGHT_NAME_1_H,
	RIGHT_NAME_1_IL,
	RIGHT_NAME_1_J,
	RIGHT_NAME_1_K,
	RIGHT_NAME_1_M,
RIGHT_NAME_1_DP};

const lcd_character RIGHT_NAME_2 = {
	RIGHT_NAME_2_A,
	RIGHT_NAME_2_B,
	RIGHT_NAME_2_C,
	RIGHT_NAME_2_D,
	RIGHT_NAME_2_E,
	RIGHT_NAME_2_F,
	RIGHT_NAME_2_G1,
	RIGHT_NAME_2_G2,
	RIGHT_NAME_2_H,
	RIGHT_NAME_2_IL,
	RIGHT_NAME_2_J,
	RIGHT_NAME_2_K,
	RIGHT_NAME_2_M,
RIGHT_NAME_2_DP};

const lcd_character RIGHT_NAME_3 = {
	RIGHT_NAME_3_A,
	RIGHT_NAME_3_B,
	RIGHT_NAME_3_C,
	RIGHT_NAME_3_D,
	RIGHT_NAME_3_E,
	RIGHT_NAME_3_F,
	RIGHT_NAME_3_G1,
	RIGHT_NAME_3_G2,
	RIGHT_NAME_3_H,
	RIGHT_NAME_3_IL,
	RIGHT_NAME_3_J,
	RIGHT_NAME_3_K,
	RIGHT_NAME_3_M,
RIGHT_NAME_3_DP};

const lcd_character RIGHT_NAME_4 = {
	RIGHT_NAME_4_A,
	RIGHT_NAME_4_B,
	RIGHT_NAME_4_C,
	RIGHT_NAME_4_D,
	RIGHT_NAME_4_E,
	RIGHT_NAME_4_F,
	RIGHT_NAME_4_G1,
	RIGHT_NAME_4_G2,
	RIGHT_NAME_4_H,
	RIGHT_NAME_4_IL,
	RIGHT_NAME_4_J,
	RIGHT_NAME_4_K,
	RIGHT_NAME_4_M,
RIGHT_NAME_4_DP};

const lcd_character RIGHT_NAME_5 = {
	RIGHT_NAME_5_A,
	RIGHT_NAME_5_B,
	RIGHT_NAME_5_C,
	RIGHT_NAME_5_D,
	RIGHT_NAME_5_E,
	RIGHT_NAME_5_F,
	RIGHT_NAME_5_G1,
	RIGHT_NAME_5_G2,
	RIGHT_NAME_5_H,
	RIGHT_NAME_5_IL,
	RIGHT_NAME_5_J,
	RIGHT_NAME_5_K,
	RIGHT_NAME_5_M,
RIGHT_NAME_5_DP};

const lcd_character RIGHT_NAME_6 = {
	RIGHT_NAME_6_A,
	RIGHT_NAME_6_B,
	RIGHT_NAME_6_C,
	RIGHT_NAME_6_D,
	RIGHT_NAME_6_E,
	RIGHT_NAME_6_F,
	RIGHT_NAME_6_G1,
	RIGHT_NAME_6_G2,
	RIGHT_NAME_6_H,
	RIGHT_NAME_6_IL,
	RIGHT_NAME_6_J,
	RIGHT_NAME_6_K,
	RIGHT_NAME_6_M,
RIGHT_NAME_6_DP};

const lcd_character* RIGHT_NAME_CHARACTERS[6] = {&RIGHT_NAME_1,&RIGHT_NAME_2,&RIGHT_NAME_3,&RIGHT_NAME_4,&RIGHT_NAME_5,&RIGHT_NAME_6};
const lcd_string RIGHT_NAME = {.length=6,.characters=RIGHT_NAME_CHARACTERS};
	
const lcd_character LEFT_MEMORY_PREFIX = {
	LEFT_MEMORY_PREFIX_A,
	LEFT_MEMORY_PREFIX_B,
	LEFT_MEMORY_PREFIX_C,
	LEFT_MEMORY_PREFIX_D,
	LEFT_MEMORY_PREFIX_E,
	LEFT_MEMORY_PREFIX_F,
	LEFT_MEMORY_PREFIX_G,
	LEFT_MEMORY_PREFIX_G,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE};
	
const lcd_character LEFT_MEMORY_TENS = {
	LEFT_MEMORY_TENS_A,
	LEFT_MEMORY_TENS_B,
	LEFT_MEMORY_TENS_C,
	LEFT_MEMORY_TENS_D,
	LEFT_MEMORY_TENS_E,
	LEFT_MEMORY_TENS_F,
	LEFT_MEMORY_TENS_G,
	LEFT_MEMORY_TENS_G,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE};
	
const lcd_character LEFT_MEMORY_UNITS = {
	LEFT_MEMORY_UNITS_A,
	LEFT_MEMORY_UNITS_B,
	LEFT_MEMORY_UNITS_C,
	LEFT_MEMORY_UNITS_D,
	LEFT_MEMORY_UNITS_E,
	LEFT_MEMORY_UNITS_F,
	LEFT_MEMORY_UNITS_G,
	LEFT_MEMORY_UNITS_G,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE};

const lcd_character* LEFT_MEMORY_CHARACTERS[6] = {&LEFT_MEMORY_PREFIX,&LEFT_MEMORY_TENS,&LEFT_MEMORY_UNITS};
const lcd_string LEFT_MEMORY = {.length=6,.characters=LEFT_MEMORY_CHARACTERS};
	
const lcd_character RIGHT_MEMORY_PREFIX = {
	RIGHT_MEMORY_PREFIX_A,
	RIGHT_MEMORY_PREFIX_B,
	RIGHT_MEMORY_PREFIX_C,
	RIGHT_MEMORY_PREFIX_D,
	RIGHT_MEMORY_PREFIX_E,
	RIGHT_MEMORY_PREFIX_F,
	RIGHT_MEMORY_PREFIX_G,
	RIGHT_MEMORY_PREFIX_G,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE};

const lcd_character RIGHT_MEMORY_TENS = {
	RIGHT_MEMORY_TENS_A,
	RIGHT_MEMORY_TENS_B,
	RIGHT_MEMORY_TENS_C,
	RIGHT_MEMORY_TENS_D,
	RIGHT_MEMORY_TENS_E,
	RIGHT_MEMORY_TENS_F,
	RIGHT_MEMORY_TENS_G,
	RIGHT_MEMORY_TENS_G,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE};

const lcd_character RIGHT_MEMORY_UNITS = {
	RIGHT_MEMORY_UNITS_A,
	RIGHT_MEMORY_UNITS_B,
	RIGHT_MEMORY_UNITS_C,
	RIGHT_MEMORY_UNITS_D,
	RIGHT_MEMORY_UNITS_E,
	RIGHT_MEMORY_UNITS_F,
	RIGHT_MEMORY_UNITS_G,
	RIGHT_MEMORY_UNITS_G,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE,
	SEGMENT_LOCATION_NONE};

const lcd_character* RIGHT_MEMORY_CHARACTERS[6] = {&RIGHT_MEMORY_PREFIX,&RIGHT_MEMORY_TENS,&RIGHT_MEMORY_UNITS};
const lcd_string RIGHT_MEMORY = {.length=6,.characters=RIGHT_MEMORY_CHARACTERS};
	
